[[qwt]]
arch = "x86_64"
git-tree-sha1 = "52cff6b1e39a034624ca4d74eb0ef473086b2418"
libc = "glibc"
os = "linux"

    [[qwt.download]]
    sha256 = "5f26730f7b2767a5abd7bfb9cd8ab127b631665276406e7fabce9af9806efc1f"
    url = "https://github.com/JuliaBinaryWrappers/qwt_jll.jl/releases/download/qwt-v6.0.0+0/qwt.v6.0.0.x86_64-linux-gnu.tar.gz"
[[qwt]]
arch = "x86_64"
git-tree-sha1 = "d9af2a5f3a715a01bd84f9ef0f03984103caf149"
os = "windows"

    [[qwt.download]]
    sha256 = "bcdf9c2aa124ba21c047a1d0bc6b6a31f6e48faccb0b33010869ee05cbe2886c"
    url = "https://github.com/JuliaBinaryWrappers/qwt_jll.jl/releases/download/qwt-v6.0.0+0/qwt.v6.0.0.x86_64-w64-mingw32.tar.gz"
