# Autogenerated wrapper script for qwt_jll for x86_64-w64-mingw32
export qwt

using Qt_jll
using GLEW_jll
using GLFW_jll
using GLU_jll
JLLWrappers.@generate_wrapper_header("qwt")
JLLWrappers.@declare_library_product(qwt, "qwt.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qt_jll, GLEW_jll, GLFW_jll, GLU_jll)
    JLLWrappers.@init_library_product(
        qwt,
        "bin\\qwt.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
